### ISSUE TITLE
Sensor icon changes on custom friendly name

### ISSUE THREAD

**Issue by Skons** [Skons/hassio-addons#11]
The icon becomes an eye when the custom friendly name is used, probably explicitly defining the icon upon update will solve this issue

**Comment by BebeMischa** [comment]
I'm now testing, if it will stay a gas tank after manually changing the icon back. Will keep you informed.... ;-)

**Comment by BebeMischa** [comment]
After manual edit the icons never change again, so I will see that as a minor issue ;-)
