### ISSUE TITLE
[brand] eerste sensor wordt niet weergegeven

### ISSUE THREAD

**Issue by Calimerorulez** [Skons/hassio-addons#14]
Bij de huidige versie, die ik geconfigureerd heb met 3 resultaten, komt het merk/brand van de eerste sensor niet mee:

![image](https://user-images.githubusercontent.com/1130552/143720182-8b98a557-41c8-48a2-8ded-82e1a17957fe.png)

**Comment by BebeMischa** [comment]
Gezien ik er geen last van heb, een hint voor de developers: Het bevuste station komt vast niet goed door... ;-)

**Comment by BebeMischa** [comment]
Hier heb ik nooit last van dit fenomeen, dus tipje voor de developers: Het ligt vast aan dat bewuste station... ;-)

**Comment by Calimerorulez** [comment]
Die pech heb ik weer :P

Hij heeft het wel even gedaan, maar na het updaten door een automation is ie ermee gestopt.

**Comment by Skons** [comment]
De Brand komt uit de data van directlease.nl. Als die daar niet in zit, kan de addon deze ook niet presenteren
![image](https://user-images.githubusercontent.com/13225002/143850860-347a2db4-3937-4eee-94a0-192db2aca9dc.png)
