### ISSUE TITLE
Dutch Gas Prices: mqtt client lost connection

### ISSUE THREAD

**Issue by MedicoreV8** [Skons/hassio-addons#20]
I haven't really been able to configure this addon and get it up and running because the log keeps reporting it can't connect to mqtt.
I am running the official Mosquitto broker.
(Also, I find the documentation still a bit vague, where exactly do I configure the examples given in the documentation?)

This is output from my log:

 -----------------------------------------------------------
 Add-on: Dutch gas prices
 Get gas prices from dutch gas stations
-----------------------------------------------------------
 Add-on version: 2022.1.2.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 7.4  (armv7 / raspberrypi4)
 Home Assistant Core: 2022.2.6
 Home Assistant Supervisor: 2022.01.1
-----------------------------------------------------------
[2022-02-14 16:04:17] INFO    : Connected with result code 5
[2022-02-14 16:04:17] ERROR   : mqtt client lost connection. Will try to reconnect once in 15s.

**Comment by MedicoreV8** [comment]
I had to manually add the Username and Password as configured in the MQTT Broker.

**Comment by Yasp0** [comment]
I have this same issue.

@MedicoreV8 where did you add the Username and Password?

And what host and port you used?

**Comment by Skons** [comment]
You can do that in the configuration tab of the addon, probably you'll have to press "Show unused optional configuration properties" at the bottom. As for your port and host, it depends on your mqtt broker. If you'll use the default, you'll probably do not have to change anything, but if you'll have to it is your HA address and port 1883

**Comment by Yasp0** [comment]
Thanks. That works indeed, in the logs I see:

[12:32:56] INFO: Starting dutch gas prices...
[2022-07-27 12:32:56] INFO    : DGP initialized, launching client
[2022-07-27 12:32:56] INFO    : Connecting mqtt
[2022-07-27 12:32:57] INFO    : Connected with result code 0

But I still see no  gas sensors in the HA development tools. The only what shows up is:

update.dutch_gas_prices_update

**Comment by Skons** [comment]
They don’t appear magically, you’ll have to follow the documentation. If you still experience problems please open a new issue and provide what you have done preferably with debug logging
