### ISSUE TITLE
LPG, Autogas doesn't work 

### ISSUE THREAD

**Issue by Dutchy-79** [Skons/hassio-addons#27]
When pulling fuel_type lpg it gives you a error that you must use autogas, when using autogas it does the same.

[2022-03-20 17:37:23] INFO    : Received payload '{"station_id":3580,"fuel_type":"autogas"}' on topic 'dgp/gas_station'
[2022-03-20 17:37:23] ERROR   : Unable to process stationid '3580' with fuel_type 'autogas', error: ''autogas''

[2022-03-20 17:44:10] INFO    : Received payload '{"station_id":3580,"fuel_type":"lpg"}' on topic 'dgp/gas_station'
[2022-03-20 17:44:10] ERROR   : Unable to validate payload '{"station_id":3580,"fuel_type":"lpg"}' for gas_station with error: ''lpg' is not one of ['euro95', 'euro98', 'diesel', 'autogas']
Failed validating 'enum' in schema['properties']['fuel_type']:
    {'enum': ['euro95', 'euro98', 'diesel', 'autogas'], 'type': 'string'}
On instance['fuel_type']:
    'lpg''

**Comment by Florian14490** [comment]
I wanted to open issue also, exact same problem here.

Hope there is a fix for it.

**Comment by Wxam** [comment]
I think you need to change the Fuel type to autogas, think your problem will be fixed then ;)

**Comment by Florian14490** [comment]
Thanks for reply but just like the issue starter. I tried lpg and autogas as fueltype. Same logs error/issue like issue-starter.

So no its not working

**Comment by Wxam** [comment]
I just found out that mine isn't working either anymore and I use the normal euro95 it gives me errors too, about being unable to publish the payload etc... Think we gotta wait for Skons answer.

**Comment by BebeMischa** [comment]
Just for reference, here using euro98 works fine.

**Comment by Florian14490** [comment]
95 and 98 works fine here also.
Also with gps location and lowest price 1 2,3 etc

Awesome Addon.
But would be nice for me lpg is also working .

**Comment by Wxam** [comment]
Hmm I for some reason get a error message since a couple of days for 95.

```
[2022-03-21 08:58:16] ERROR   : Unable to process payload '{'fuel_type': 'euro95', 'radius': 5, 'latitude': 52.509374787853304, 'longitude': 4.990115761756898, 'to_publish': 6}' with error: ''<' not supported between instances of 'NoneType' and 'float''
[2022-03-21 08:58:16] INFO    : publishing status to mqtt
[2022-03-21 08:58:16] DEBUG   : on_message: received the topic 'homeassistant/sensor/dgp/status/config'
[2022-03-21 08:58:17] DEBUG   : publish_status: Waiting for discovery on topic 'homeassistant/sensor/dgp/status/config'
[2022-03-21 08:58:17] DEBUG   : publish_status: Autodiscover 'True', State 'True' and Attributes 'True'
[2022-03-21 08:58:17] INFO    : publishing status done
```

Haven't changed anything in the last couple of days on the addon it just stopped working all of the sudden.

**Comment by BebeMischa** [comment]
Do I see same unwanted spaces in your payload, @Wxam ?

**Comment by Wxam** [comment]
> Do I see same unwanted spaces in your payload, @Wxam ?

![image](https://user-images.githubusercontent.com/20145041/159229805-1366ee11-8fb4-4ded-8290-b7478c7a258f.png)

This is my Automation with the payload_template in it. I did a copy paste from the installation document itself just changed person.skons to zone.home and the to_publish to 6

**Comment by Dutchy-79** [comment]
@Wxam that looks like a different error to me, maybe make a separate issue for this.

**Comment by Wxam** [comment]
> @Wxam that looks like a different error to me, maybe make a separate issue for this.

Will do that! thanks for the suggestion

EDIT: Link to my issue: https://github.com/Skons/hassio-addons/issues/28

**Comment by Skons** [comment]
LPG was not correctly implemented, with 2022.3.21.1 there is better support for LPG, autogas should not be used as fueltype in the payload. If there are any issues please let me know.

**Comment by Florian14490** [comment]
Kevin, nice. Thanks for the fix. I dont see the update to new version. Or do I have to copy manual the updated files in right folder using samba share?

**Comment by Skons** [comment]
It can take a while, but if you want to force the update: go to addons in ha, click on “add-on store”, click the hamburger menu at the top and select “check for updates”. The update should be available now

**Comment by Florian14490** [comment]
Oh, thats a lot faster haha, I just removed addon and repositry and installed it back. Then he get also the new files.

**Comment by Dutchy-79** [comment]
Thanks, works fine for me now.

**Comment by Florian14490** [comment]
Kevin, nice. Thanks for the fix. I dont see the update to new version. Or do I have to copy manual the updated files in right folder using samba share?

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by Skons** [comment]
What is the version you are currently running? Go to settings -> Addons -> Dutch Gas Prices and on the top you can see Current Version
