### ISSUE TITLE
Second person add for check lowest gas prices

### ISSUE THREAD

**Issue by Florian14490** [Skons/hassio-addons#30]
Hi Skons,

Issue: Make a second automation with a person location to find lowest_gas_prices nearby the second person.

It will now overwrite the first person location (other automation). the Lowest_gasprice entities wil now be on the second person. 

Is it possible to make an entity as followed?
sensor.gas_station_person.1_fueltype_lowest_price_1 
sensor.gas_station_person.2_fueltype_lowest_price_1 

Hope there's a solution.

Keep up the good work, its a good addon !

Greetz Florian

**Comment by Skons** [comment]
Great idea, just released this, you can find how to use this through
https://github.com/Skons/hassio-addons/blob/main/dutch_gas_prices/DOCS.md#identifier
