### ISSUE TITLE
error on install

### ISSUE THREAD

**Issue by Rozenlaan** [Skons/hassio-addons#51]
Trying to install and have this error:

The command '/bin/bash -o pipefail -c apk add --no-cache --virtual .build-dependencies=20230531.221623 tesseract-ocr=5.3.1-r1 tesseract-ocr-dev=5.3.1-r1 jpeg-dev=9e-r1 libjpeg=9e-r1 zlib-dev=1.2.13-r1 gcc=12.2.1_git20220924-r10 libc-dev=0.7.2-r5' returned a non-zero code: 91

Home Assistant 2023.7.3
Supervisor 2023.07.1
Operating System 10.3
Frontend-versie: 20230705.1 - latest

**Comment by HMvdZijden** [comment]
Exactly the same here.

**Comment by DutchCoban** [comment]
Same here, running HA in a VM on my Synology.
Home Assistant 2023.8.1
Supervisor 2023.07.1
Operating System 10.4
Frontend 20230802.0 - latest

**Comment by Quevinsta** [comment]
Also here. Same specs as crispy78.

**Comment by Skons** [comment]
I found a solution, but #52 needs to be solved also

**Comment by Skons** [comment]
Issue fixed with PR #53 .
