### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by Skons** [Skons/hassio-addons#52]
The webservice responds with the error below. This is related to the header used.

There is currently active development in regards to scraping. The solution needs to be a bit more resillient.

```

<html><head><title>Apache Tomcat/7.0.76 - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 403 - Toegang geweigerd; mail naar tankservice-block@app-it-up.com voor vragen</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>Toegang geweigerd; mail naar tankservice-block@app-it-up.com voor vragen</u></p><p><b>description</b> <u>Access to the specified resource has been forbidden.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.76</h3></body></html>
```

**Comment by Skons** [comment]
Fixed with #53

**Comment by Hurr1c4n3** [comment]
I got the same error again as above.
`<h1>HTTP Status 403 - Toegang geweigerd; mail naar tankservice-block@app-it-up.com voor vragen</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>Toegang geweigerd; mail naar tankservice-block@app-it-up.com voor vragen</u></p><p><b>description</b> <u>Access to the specified resource has been forbidden.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.76</h3></body></html>'
[2024-01-30 09:05:01] INFO    : There are '0' stations within range for fuel type 'euro95'`

**Comment by Skons** [comment]
How often do you update your tankstations?

**Comment by Hurr1c4n3** [comment]
The 5th minute of every hour.
`alias: Benzine prijzen thuis
description: ""
trigger:
  - platform: time_pattern
    minutes: 5
  - platform: homeassistant
    event: start
condition: []
action:
  - service: mqtt.publish
    data:
      topic: dgp/gas_stations
      payload_template: >-
        {"fuel_type":"euro95","radius":5,"latitude":52.XXX,"longitude":6.XXX,"to_publish":5}
mode: single`

**Comment by Rikkie80** [comment]
Same here with same update interval
