### ISSUE TITLE
the add-on its not working 

### ISSUE THREAD

**Issue by Homeassistjoenka** [Skons/hassio-addons#64]
the add-on is not working with newst beta version 2024.2.0b8
, we have no prices.

[dutch gas price.txt](https://github.com/Skons/hassio-addons/files/14175522/dutch.gas.price.txt)

**Comment by BebeMischa** [comment]
Inside your textfile:

```
Status report</p><p><b>message</b> <u>Toegang geweigerd; mail naar tankservice-block@app-it-up.com voor vragen</u></p><p><b>description</b> <u>Access to the specified resource has been forbidden.
```

so same as #63

**Comment by Homeassistjoenka** [comment]
oke thanks for reaction, that is not fine this, may already have a solution in mind?

**Comment by BebeMischa** [comment]
Not at this time. Just follow that other thread ;-)

**Comment by Homeassistjoenka** [comment]
how you need other thread?

**Comment by BebeMischa** [comment]
I don't. You need to follow it.

Click on this: #63 , this problem is already discussed there. There are lot of reports of this issue.

**Comment by Homeassistjoenka** [comment]
this?

That was a reaction i would have expected from them. So, there are a few things that can be done:

Disable your automatic retrieval of the prices when this message appears. Maybe you will get unblocked automatically
If you have a dynamic ip on your router (thus the internet), try to get a new one
Extend DGP with VPN/Tor functionality so that if you get this block message, another ip can be assigned. This is what i rather do not do due to complexity and it's unkown if this will solve the problem
Ask for a paid subscription with api functionality @ tankservice

**Comment by Homeassistjoenka** [comment]
the add-on was so perfect,

**Comment by Skons** [comment]
Please continue the discussion in #63
