### ISSUE TITLE
Tiende centen van benzineprijs niet getoond

### ISSUE THREAD

**Issue by Calimerorulez** [Skons/hassio-addons#8]
Hoi :)

Leuke integratie! Ik ben hem aan het installeren en configureren in Home Assistant, alleen valt het me op dat de tienden van centen niet teruggegeven worden.

Hier in de buurt kost een liter Euro 98, 2.039 bijvoorbeeld, alleen de laatste 9 wordt niet teruggegeven in de sensor.

Heb je een tip hoe dit is op te lossen?

Dank!

**Comment by Skons** [comment]
Tesseract zal hiervoor getuned moeten worden, als ik tijd heb zal ik kijken of dit gaat lukken

**Comment by Skons** [comment]
2022.1.2.1 zojuist opgeleverd met aanzienlijke verbetering ten opzichte van superscript, oftewel de tienden. Deze worden nu wel getoond. Nu is het wel zo dat ik het niet echt beter krijg dan hoe het nu is. Soms wordt bijvoorbeeld een 8 voor een 3 of een 9 aangezien. Mijn vorige comment zei: tesseract moet getuned worden, wat ik heb gerealiseerd is betere preprocessing zodat tesseract de cijfers beter kan herkennen. Het is mij nog wel onduidelijk waarom soms een 8 voor bv een 3 aangezien wordt. Ogenschijnlijk dezelfde 8 wordt in het ene geval wel goed herkend, maar in een ander geval niet 🤷‍♂️

**Comment by Calimerorulez** [comment]
Dank je wel voor je werk!
